const CRAWL_NEW_BOOK_TTV_JOB_KEY = 'new-book-ttv-job-key'
const CRAWL_STATUS_CRAWLING = 'crawling'
const CRAWL_STATUS_COMPLETED = 'completed'
const REDIS_STREAM_KEY_NEW_BOOKS = 'new-books'
const REDIS_STREAM_KEY_BOOK = 'book'
const REDIS_STREAM_KEY_CHAPTER = 'chapter'
const LAST_ID_NEW_BOOKS_STREAM_KEY = 'last_id_new_books_stream'
const LAST_ID_BOOK_STREAM_KEY = 'last_id_book_stream'
const LAST_ID_CHAPTER_STREAM_KEY = 'last_id_chapter_stream'
const ITEM_PER_PAGE = 10

const API_CODE_SUCCESS = 0
const API_CODE_ERROR = 1

module.exports = {
  CRAWL_NEW_BOOK_TTV_JOB_KEY,
  CRAWL_STATUS_CRAWLING,
  CRAWL_STATUS_COMPLETED,
  REDIS_STREAM_KEY_NEW_BOOKS,
  LAST_ID_NEW_BOOKS_STREAM_KEY,
  REDIS_STREAM_KEY_BOOK,
  REDIS_STREAM_KEY_CHAPTER,
  LAST_ID_BOOK_STREAM_KEY,
  LAST_ID_CHAPTER_STREAM_KEY,
  ITEM_PER_PAGE,
  API_CODE_ERROR,
  API_CODE_SUCCESS,
}
